#!/bin/bash

docker build \
    --file $(echo "${DOCKERFILE_PATH}"  | cut -d '.' -f 1) \
    --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
    --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
    --tag "$IMAGE_NAME" \
    .
